baseURL = "https://hejfelix.github.io/fp-blog/"
languageCode = "en-us"
title = "Felix' FP-Blog"
theme = [ "beautifulhugo" ]

[Author]
  name = "Felix Bj√¶rt Hargreaves"
  github = "hejfelix"
  twitter = "FelixHargreaves"
  linkedin = "felix-hargreaves-9b0b3035"
  stackoverflow = "users/238100/felix"

[markup.highlight]
    codeFences = true
    style = "tango"
    tabWidth = 4